apiVersion: apps/v1
kind: Deployment
metadata:
  name: url-shortener
  labels:
    app: url-shortener
spec:
  replicas: 3
  selector:
    matchLabels:
      app: url-shortener
  template:
    metadata:
      labels:
        app: url-shortener
    spec:
      containers:
        - name: url-shortener
          image: url-shortener:latest
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: db-storage
              mountPath: /app
      volumes:
        - name: db-storage
          emptyDir: {}